export const PROVINCIAS = [
  "Buenos Aires",
  "CABA",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
] as const

export type Provincia = (typeof PROVINCIAS)[number]

export const CIUDADES_POR_PROVINCIA: Record<string, string[]> = {
  "Buenos Aires": [
    "La Plata",
    "Mar del Plata",
    "Bahía Blanca",
    "Tandil",
    "Quilmes",
    "Lanús",
    "Avellaneda",
    "Lomas de Zamora",
    "Morón",
    "San Isidro",
    "Vicente López",
    "Tigre",
    "Pilar",
    "San Nicolás",
    "Zárate",
    "Campana",
    "Luján",
    "Mercedes",
    "Junín",
    "Pergamino",
    "Olavarría",
    "Necochea",
    "Tres Arroyos",
  ],
  CABA: [
    "Balvanera",
    "Barracas",
    "Belgrano",
    "Boedo",
    "Caballito",
    "Chacarita",
    "Coghlan",
    "Colegiales",
    "Constitución",
    "Flores",
    "Floresta",
    "La Boca",
    "Liniers",
    "Mataderos",
    "Monte Castro",
    "Monserrat",
    "Nueva Pompeya",
    "Núñez",
    "Palermo",
    "Parque Avellaneda",
    "Parque Chacabuco",
    "Parque Chas",
    "Parque Patricios",
    "Paternal",
    "Puerto Madero",
    "Recoleta",
    "Retiro",
    "Saavedra",
    "San Cristóbal",
    "San Nicolás",
    "San Telmo",
    "Versalles",
    "Villa Crespo",
    "Villa del Parque",
    "Villa Devoto",
    "Villa Lugano",
    "Villa Luro",
    "Villa Ortúzar",
    "Villa Pueyrredón",
    "Villa Real",
    "Villa Riachuelo",
    "Villa Santa Rita",
    "Villa Soldati",
    "Villa Urquiza",
  ],
  Catamarca: ["San Fernando del Valle de Catamarca", "Andalgalá", "Belén", "Tinogasta"],
  Chaco: ["Resistencia", "Presidencia Roque Sáenz Peña", "Villa Ángela", "Charata"],
  Chubut: ["Rawson", "Comodoro Rivadavia", "Trelew", "Puerto Madryn", "Esquel"],
  Córdoba: [
    "Córdoba",
    "Villa Carlos Paz",
    "Río Cuarto",
    "Villa María",
    "San Francisco",
    "Alta Gracia",
    "Jesús María",
    "La Falda",
    "Bell Ville",
  ],
  Corrientes: ["Corrientes", "Goya", "Paso de los Libres", "Mercedes", "Curuzú Cuatiá"],
  "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú", "Concepción del Uruguay", "Colón"],
  Formosa: ["Formosa", "Clorinda", "Pirané", "El Colorado"],
  Jujuy: ["San Salvador de Jujuy", "Palpalá", "Libertador General San Martín", "Perico"],
  "La Pampa": ["Santa Rosa", "General Pico", "Toay", "General Acha"],
  "La Rioja": ["La Rioja", "Chilecito", "Aimogasta", "Chamical"],
  Mendoza: ["Mendoza", "San Rafael", "Godoy Cruz", "Guaymallén", "Las Heras", "Luján de Cuyo", "Maipú"],
  Misiones: ["Posadas", "Oberá", "Eldorado", "Puerto Iguazú", "Apóstoles"],
  Neuquén: ["Neuquén", "San Martín de los Andes", "Zapala", "Cutral Có", "Centenario"],
  "Río Negro": ["Viedma", "San Carlos de Bariloche", "General Roca", "Cipolletti", "Villa Regina"],
  Salta: ["Salta", "San Ramón de la Nueva Orán", "Tartagal", "Metán", "Cafayate"],
  "San Juan": ["San Juan", "Rawson", "Chimbas", "Rivadavia", "Santa Lucía"],
  "San Luis": ["San Luis", "Villa Mercedes", "Merlo", "La Punta"],
  "Santa Cruz": ["Río Gallegos", "Caleta Olivia", "El Calafate", "Pico Truncado"],
  "Santa Fe": ["Santa Fe", "Rosario", "Rafaela", "Venado Tuerto", "Reconquista", "Villa Gobernador Gálvez"],
  "Santiago del Estero": ["Santiago del Estero", "La Banda", "Termas de Río Hondo", "Añatuya"],
  "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin"],
  Tucumán: ["San Miguel de Tucumán", "Yerba Buena", "Tafí Viejo", "Concepción", "Banda del Río Salí"],
}

export function getCiudadesByProvincia(provincia: string): string[] {
  return CIUDADES_POR_PROVINCIA[provincia] || []
}
